main:
	g++ -g *.cpp -std=c++98 -pedantic -o main

clean:
	rm -f *.o *.tar.gz main
	reset
	clear

run:
	./main

tar:
	tar -cvz *.h *.cpp -f Mulisa_Friend_Assignment_3_Part_1.tar.gz

untar_gz:
	tar -zxvf *.tar.gz